require:
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  NewCops: enable
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
#-------------------------------------------------------------------------------
RSpec/ExampleLength:
  Exclude:
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/records_handler_spec.rb
RSpec/FilePath:
  Exclude:
    - spec/register_ingester_sk.rb
    - spec/unit/apps/ingester_spec.rb
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/record_serializer_spec.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/records_producer_spec.rb
RSpec/MessageSpies:
  Exclude:
    - spec/unit/apps/ingester_spec.rb
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/records_producer_spec.rb
RSpec/MultipleExpectations:
  Exclude:
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/records_producer_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/unit/records_producer_spec.rb
RSpec/NamedSubject:
  Exclude:
    - spec/unit/apps/ingester_spec.rb
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/record_serializer_spec.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/records_producer_spec.rb
RSpec/StubbedMock:
  Exclude:
    - spec/unit/apps/ingester_spec.rb
    - spec/unit/records_handler_spec.rb
RSpec/VerifiedDoubles:
  Exclude:
    - spec/unit/apps/ingester_spec.rb
    - spec/unit/clients/sk_client_spec.rb
    - spec/unit/records_handler_spec.rb
    - spec/unit/records_producer_spec.rb
